### ISSUE TITLE
Add to CLI to start more databases

### ISSUE THREAD

**Issue by luccabassoli** [rinckodev/constatic#1]
I think this CLI is perfect, but I think that to make it even more perfect you could start the project with PrismaORM, a database ORM that is widely used and easy to use by the community, what do you think?

**Comment by rinckodev** [comment]
It's already in my plans, it will be added soon https://github.com/rinckodev/constatic/blob/main/templates/discord/bot/properties.json

**Comment by luccabassoli** [comment]
> Já está nos meus planos, será adicionado em breve https://github.com/rinckodev/constatic/blob/main/templates/discord/bot/properties.json

Right, thanks!

**Comment by luccabassoli** [comment]
It was already in the developer's plans, thank you
